### ISSUE TITLE
Single track support - Issue when tracks list size is 1 

### ISSUE THREAD

**Issue by chaps** [noahfx/lobster#5]
When using only one item in the tracks list file,
an index error is raised as the `end_time` is calculated with the next item's `initial_time`
value.

```
Traceback (most recent call last):
  File "/.../bin/lobster", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/.../bin/lobster", line 49, in <module>
    generate_album(**kwargs)
  File "/.../bin/lobster", line 27, in generate_album
    create_tracks(media_file_src, output, audio_segments,
  File "/.../lobster/audio.py", line 98, in create_tracks
    splitted_segments = split_audio(source_media, get_workingdir(),
  File "/.../lobster/audio.py", line 57, in split_audio
    s_audio_segments = build_time_range(len(audio_orig), audio_segments)
  File "/.../lobster/audio.py", line 40, in build_time_range
    nxt_stream_init_t = sortedStreamSegments[idx + 1].initial_time
IndexError: list index out of range
```

**Comment by noahfx** [comment]
Merged! Thanks!
